config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions,   only: :create
  resources :exceptions, only: :create
  
  get 'users/deactivate'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exceptions_controller.rb
class ExceptionsController < ApplicationController
  def create
    raise "this is an exception"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    logger.info("Somebody just logged in")
    flash[:message] = "We just logged a fake login"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def deactivate
    logger.warn("Somebody just deactivated their account")
    flash[:message] = "We just logged a fake account deactivation"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exceptions_helper.rb
module ExceptionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <div class="row" style="margin-left: 0px;">
      <div class="col">
        <h3>Click these links to log events for a: </h3>
        <ul>
          <li><%= link_to "Login", sessions_path, method: :post %></li>
          <li><%= link_to "User Deactivation", users_deactivate_path %></li>
          <li><%= link_to "500 error", exceptions_path, method: :post %></li>
        </ul>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JsonLoggingRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row main-content">
      <div class="header col">
        <h1>This is an app that spits out logs</h1>
      </div>

      <div class="col">
        <% if flash[:message] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:message] %>
        </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>